stages:
  - build
  - deploy

build:
  stage: build
  retry: 2
  variables:
    VERSION: "$CI_PIPELINE_IID"
  tags:
    - docker-runner
  script:
    - docker build -t my.repo.com/exchange:$VERSION . --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
      changes: 
        - Dockerfile
        - Exchange/**
        - requirements.txt

deploy(exchange):
  stage: deploy
  when: manual
  tags:
    - shell-runner
  variables:
    PROJECT_DIR: "services/exchange/"
    DEPLOYMENT_FILE1: "exchange.yaml"
    DEPLOYMENT_FILE2: "db-migration.yaml"
    DEPLOYMENT_FILE3: "exchange-django-q.yaml"
  script:
    - git clone https://my.repo.com/devops.git
    - cd $PROJECT_DIR
    - sed -i "s|your-registry/exchange:.*|your-registry/exchange:$VERSION|g" ${DEPLOYMENT_FILE1}
    - sed -i "s|your-registry/exchange:.*|your-registry/exchange:$VERSION|g" ${DEPLOYMENT_FILE2}
    - sed -i "s|your-registry/exchange:.*|your-registry/exchange:$VERSION|g" ${DEPLOYMENT_FILE3}
    - git commit -am "Deploy exchange version $VERSION"
    - git push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
      changes: 
        - Dockerfile
        - Exchange/**
        - requirements.txt